// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package api

// Status defines model for status.
type Status struct {

	// Status code
	Code int32 `json:"code"`

	// Status message
	Message string `json:"message"`
}

// InvoiceResponse defines model for invoice_response.
type InvoiceResponse string

// Statusresponse defines model for statusresponse.
type Statusresponse Status

// GetInvoiceParams defines parameters for GetInvoice.
type GetInvoiceParams struct {

	// the receipt code
	Code string `json:"code"`
}

// PrintJSONBody defines parameters for Print.
type PrintJSONBody struct {
	PdfUrl string `json:"pdf_url"`
}

// PrintJSONRequestBody defines body for Print for application/json ContentType.
type PrintJSONRequestBody PrintJSONBody
